### PR TITLE
Refactor

### PR DESCRIPTION
**Pull request by Speakus**
fix compilation

### CODE REVIEW

**Comment by b123400** [comment]
Hello! Thank you very much for the PR, can you successfully build the project? I cloned your pull request and I couldn't. Nothing is wrong with this PR though.

- `pod install` fails. The `FGTranslatorDemo/Podfile` file is 2 years old and it doesn't support [the "new" Podfile DSL](http://blog.cocoapods.org/CocoaPods-1.0/).
- `XMLDictionary`'s sources should be in the `FGTranslator/XMLDictionary` directory, it should work without being added to Podspec. I don't know why the original author copied the source instead of adding it to Podspec, but I think using Cocoapods makes more sense too. It will be nice if you delete the copied source after changing the spec.

**Comment by Speakus** [comment]
I did not use `pod install` to compile

**Comment by Speakus** [comment]
XMLDictionary better to use through dependency to allow use this pod and XMLDictionary pod simultaneously

**Comment by Speakus** [comment]
@b123400 I fixed pod install + remove XMLDictionary from project. Now it could be compiled after pod install command

**Review by b123400 — APPROVED** [review]
Thank you very much, it works perfectly :)

**Pull request merged**
